app configs aware chronicle api
openlattice/chronicle-api pull request #38
Opened 2020-10-21 21:51 UTC by anzioka

PR:
Separate app configs aware api endpoints from legacy endpoints

2020-10-28 18:42 UTC, makosblade submitted a review, later dismissed

2020-10-29 02:00 UTC, UnsungHero97 requested changes

2020-10-29 02:00 UTC, UnsungHero97 commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +            @Path( DATASOURCE_ID ) String deviceId,
Is it a data source id or a device id. Let's be consistent (i.e. data source).

2020-10-29 12:51 UTC, anzioka commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +            @Path( DATASOURCE_ID ) String datasourceId,
The Datasource object is an `Optional`

2020-10-29 12:53 UTC, anzioka commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +    Void deleteParticipantAndAllNeighbors(
Why would that be problematic?

2020-10-29 13:38 UTC, anzioka commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +            + ENTITY_KEY_ID_PATH )
The current pattern is consistent with the legacy api

2020-10-29 13:42 UTC, anzioka commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +    @GET( BASE + AUTHENTICATED + PARTICIPANT_PATH + DATA_PATH + ORGANIZATION_ID_PATH + STUDY_ID_PATH
https://github.com/openlattice/chronicle-api/pull/38#discussion_r514264380

2020-10-29 13:42 UTC, anzioka commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +    @GET( BASE + AUTHENTICATED + PARTICIPANT_PATH + DATA_PATH + ORGANIZATION_ID_PATH + STUDY_ID_PATH
https://github.com/openlattice/chronicle-api/pull/38#discussion_r514264380

2020-10-29 14:16 UTC, anzioka commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +    Map<String, UUID> getPropertyTypeIds( @Body Set<String> propertyTypeFqns );
We could, but that sounds like unnecessary overhead work on the android client

2020-10-29 22:06 UTC, UnsungHero97 commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +    Void deleteParticipantAndAllNeighbors(
Something about Spring truncating `@PathVariable` strings with dots...

https://www.baeldung.com/spring-mvc-pathvariable-dot

> Spring considers that anything behind the last dot is a file extension

Look at `PrincipalApi` for how we support email searches.

2020-10-29 22:07 UTC, UnsungHero97 commented on src/main/java/com/openlattice/chronicle/api/ChronicleApi.java
> +            + ENTITY_KEY_ID_PATH )
Why are you trying to be consistent with the legacy api?

2020-11-25 23:41 UTC, UnsungHero97 approved these changes

2020-11-25 23:53 UTC, giuliacampana approved these changes

2020-11-25 23:54 UTC, merged