register candidate
openlattice/chronicle-api pull request #74
Opened 2022-01-27 00:55 UTC by UnsungHero97

2022-01-27 06:22 UTC, geekbeast approved these changes

2022-01-27 06:33 UTC, geekbeast requested changes

2022-01-27 06:33 UTC, geekbeast commented on src/main/kotlin/com/openlattice/chronicle/candidates/Candidate.kt
> +    val dob: String?
Wait a sec-- just realized this is a string. Should definitely be a LocalDate

2022-01-28 00:31 UTC, solomontang approved these changes

2022-01-29 00:29 UTC, njhlai approved these changes

2022-01-29 00:38 UTC, anzioka approved these changes

2022-01-29 00:42 UTC, solomontang approved these changes

2022-01-29 00:43 UTC, merged