match pojo with frontend json prop names
openlattice/chronicle-api pull request #85
Opened 2022-02-11 22:32 UTC by and-carter

2022-02-11 22:38 UTC, anzioka approved these changes

2022-02-12 00:18 UTC, geekbeast approved these changes
Will this actually be backwards compatible?

2022-02-12 00:24 UTC, UnsungHero97 requested changes

2022-02-12 00:24 UTC, UnsungHero97 commented on src/main/kotlin/com/openlattice/chronicle/timeusediary/TimeUseDiaryResponse.kt
> +        val question: String,
Missing `ol.code`.

2022-02-12 07:39 UTC, geekbeast approved these changes

2022-02-12 07:43 UTC, merged