Task/lattice 3062 questionnaires api
openlattice/chronicle-api pull request #98
Opened 2022-02-20 22:19 UTC by anzioka

2022-02-20 22:48 UTC, UnsungHero97 requested changes

2022-02-20 22:48 UTC, UnsungHero97 commented on src/main/kotlin/com/openlattice/chronicle/survey/SurveyApi.kt
> +    @GET(BASE  +  STUDY_ID_PATH + PARTICIPANT_ID + PARTICIPANT_ID_PATH + APP_USAGE_PATH)
```suggestion
    @GET(BASE  +  STUDY_ID_PATH + PARTICIPANT_PATH + PARTICIPANT_ID_PATH + APP_USAGE_PATH)
```

2022-02-20 22:48 UTC, UnsungHero97 commented on src/main/kotlin/com/openlattice/chronicle/survey/SurveyApi.kt
> +    @POST(BASE + STUDY_ID_PATH + PARTICIPANT_ID + PARTICIPANT_ID_PATH + APP_USAGE_PATH)
```suggestion
    @POST(BASE + STUDY_ID_PATH + PARTICIPANT_PATH + PARTICIPANT_ID_PATH + APP_USAGE_PATH)
```

2022-02-21 03:05 UTC, geekbeast approved these changes

2022-02-21 05:16 UTC, UnsungHero97 approved these changes

2022-02-21 05:16 UTC, merged